name: Run lint
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      run: golangci-lint run
      with:
        version: latest

