name: Run unit tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  unit-tests:
    strategy:
      matrix:
        version: [ '1.19' , '1.20' ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Run unit tests
      run: go test -v .
